apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hb-api-secret
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}